# Generated by Django 5.2.3 on 2025-06-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título curto e objetivo da tarefa.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada da tarefa.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data/hora em que a tarefa foi criada.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Data/hora em que a tarefa foi concluída.', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Indica se a tarefa foi concluída.')),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula para categorizar tarefas.', max_length=200)),
            ],
        ),
    ]
